use_frameworks!

platform :ios, '8.0'

target 'WGBRepairedOrientationLabel_Example' do
  pod 'WGBRepairedOrientationLabel', :path => '../'

  target 'WGBRepairedOrientationLabel_Tests' do
    inherit! :search_paths

    
  end
end
